---
name: Variable-Lazy
version: 0.03
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Lazy variables
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Variable-Lazy
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/variable-lazy/tree
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::More: 0
requires:
  B::Hooks::EndOfScope: 0
  Devel::Declare: 0
  Exporter: 5.57
  namespace::clean: 0
  perl: 5.008
configure_requires:
  Module::Build: 0
provides:
  Variable::Lazy:
    file: lib/Variable/Lazy.pm
    version: 0.03
  Variable::Lazy::Guts:
    file: lib/Variable/Lazy/Guts.pm
    version: 0.03
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - lazy
  - laziness
