---
name: Variable-Lazy
version: 0.02
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Lazy variables
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Variable-Lazy
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/variable-lazy/tree
requires:
  B::Hooks::EndOfScope: 0
  Devel::Declare: 0
  perl: 5.007003
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
provides:
  Variable::Lazy:
    file: lib/Variable/Lazy.pm
    version: 0.02
  Variable::Lazy::Guts:
    file: lib/Variable/Lazy/Guts.pm
    version: 0
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - lazy
  - laziness
